### ISSUE TITLE
manage Grafana's dashboards

### ISSUE THREAD

**Issue by gmauro** [usegalaxy-eu/infrastructure-playbook#244]
Add Grafana's dashboards management in Grafana's playbook
https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
https://github.com/cloudalchemy/ansible-grafana/blob/0.16.2/tasks/dashboards.yml

**Comment by gmauro** [comment]
```
root@stats:~$ cat /etc/grafana/provisioning/dashboards/usegalaxy_eu.yaml 
# # config file version
apiVersion: 1

providers:
 - name: 'usegalaxy.eu'
   orgId: 1
   folder: ''
   folderUid: ''
   type: file
   options:
     path: /data_is/monitoring/grafana_data/dashboards
     foldersFromFilesStructure: true


```
