### ISSUE TITLE
roles.yml missing

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#442]
```
roles:
  dataplant*:
    params:
      object_store_id: 'dataplant01'
  storage-test*:
    params:
      object_store_id: 's3_netapp01'




```
